name: batch_photo_tools
description: batch photo processing tool for Android.
publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^12.1.0
  image: 4.9.1
  image_gallery_saver_plus: 5.1.1
  intl: 0.20.2
  shared_preferences: 2.3.2
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/fonts/7_Segment/7_Segment.fnt
    - assets/fonts/7_Segment/page0.png
    - assets/fonts/7_Segment_Bold/7_Segment_Bold.fnt
    - assets/fonts/7_Segment_Bold/page0.png
    - assets/fonts/Film_Camera/Film_Camera.fnt
    - assets/fonts/Film_Camera/page0.png
    - assets/fonts/Film_Camera_Bold/Film_Camera_Bold.fnt
    - assets/fonts/Film_Camera_Bold/page0.png
    - assets/fonts/serif_regular/serif_regular.fnt
    - assets/fonts/serif_regular/page0.png
    - assets/fonts/serif_bold/serif_bold.fnt
    - assets/fonts/serif_bold/page0.png
    - assets/fonts/lato_regular/lato_regular.fnt
    - assets/fonts/lato_regular/page0.png
    - assets/fonts/lato_bold/lato_bold.fnt
    - assets/fonts/lato_bold/page0.png
    - assets/fonts/noto_regular/noto_regular.fnt
    - assets/fonts/noto_regular/page0.png
    - assets/fonts/noto_bold/noto_bold.fnt
    - assets/fonts/noto_bold/page0.png
    - assets/fonts/Retro_Camera/Retro_Camera.fnt
    - assets/fonts/Retro_Camera/page0.png
